resources:
    repositories:
        - repository: templates
          type: git
          name: Arquitectura/PipelineTemplates #Se define el nombre del TeamProject / Repositorio donde se encuentra el template.
          ref: refs/tags/2.25.3
trigger:
    - demo/*
    - sandbox
    - demo-sandbox/*
    - master
    - demo-prod/*
pool: CI-AgentsLinux #El agente utilizado, adentro cada template tiene su agente particular.

variables:
    FUSION_RELEASE: '7.0.2'
    NODE_VERSION: 22.x

jobs:
    - job: BuildArc
      steps:
          - bash: |
                echo "checking date"
                date
                echo "setting date to America/Argentina/Buenos_Aires"
                sudo timedatectl set-timezone "America/Argentina/Buenos_Aires"
                date
            displayName: Cambio zona horaria
          - template: Arc/build.yml@templates
            parameters:
                runTest: true
                nodeVersion: $(NODE_VERSION)
                projectKeySonarQube: arc-ln
                sonarQubeExtraProperties: |
                    sonar.sourceEncoding=UTF-8
                    sonar.sources=./
                    sonar.language=js
                    sonar.exclusions=__tests__/**,__mocks__/**,.fusion,**.test.js,node_modules,resources/**,src/statics/**
                    sonar.tests=./__tests__
                    sonar.test.inclusions=./__tests__/**/*.test.js
                    sonar.javascript.lcov.reportPaths=coverage/lcov.info
          - script: |
                curl --location 'https://api.staging.lanacionar.arcpublishing.com/pagebuilder/datasync/sync' \
                --header 'Content-Type: application/json' \
                --header "Authorization: Bearer $TOKEN_SYNC" \
                --data '{ "source": "production" }'
            condition: and(succeeded(), eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/sandbox'), eq(variables['System.PullRequest.SourceBranch'], 'refs/heads/develop'))
            displayName: Sync prod - staging environment
            env:
                TOKEN_SYNC: $(TOKEN_SYNC)
