import React from 'react';
import {
    ClearNight,
    Cloudy,
    Club,
    EmailFilled,
    Email,
    FacebookFilled,
    Facebook,
    Home,
    Instagram,
    InstagramFilled,
    Rain,
    RainyCloudy,
    Rss,
    SectionFilled,
    Snow,
    SnowCloudy,
    Storm,
    StormCloudy,
    Sun,
    SunCloudy,
    TwitterFilled,
    Twitter,
    User,
    WhatsappFilled,
    Whatsapp,
    Windy,
    SectionFilled,
    Comment,
    Copy,
    Download,
    Filter,
    Fire,
    Group,
    Knife,
    ShareAndroid,
    Share,
    Swap
} from '../../../../../resources/svg';

export const mapperIcons = {
    'facebook-filled': <FacebookFilled />,
    facebook: <Facebook />,
    'twitter-filled': <TwitterFilled />,
    twitter: <Twitter />,
    'instagram-filled': <InstagramFilled />,
    instagram: <Instagram />,
    'whatsapp-filled': <WhatsappFilled />,
    whatsapp: <Whatsapp />,
    email: <Email />,
    'email-filled': <EmailFilled />,
    rss: <Rss />,
    club: <Club />,
    comment: <Comment />,
    copy: <Copy />,
    download: <Download />,
    filter: <Filter />,
    fire: <Fire />,
    group: <Group />,
    'share-android': <ShareAndroid />,
    share: <Share />,
    swap: <Swap />,
    knife: <Knife />,
    section: <SectionFilled />,
    user: <User />,
    home: <Home />,
    rain: <Rain />,
    'rainy-cloudy': <RainyCloudy />,
    sun: <Sun />,
    'sun-cloudy': <SunCloudy />,
    cloudy: <Cloudy />,
    'storm-cloudy': <StormCloudy />,
    Snow: <Snow />,
    'clear-night': <ClearNight />,
    Windy: <Windy />,
    'snow-cloudy': <SnowCloudy />,
    Storm: <Storm />
};
