import React from 'react';
import {
    ClearNight,
    Cloudy,
    Club,
    EmailFilled,
    FacebookFilled,
    Home,
    Instagram,
    InstagramFilled,
    Rain,
    RainyCloudy,
    Rss,
    SectionFilled,
    Snow,
    SnowCloudy,
    Storm,
    StormCloudy,
    Sun,
    SunCloudy,
    TwitterFilled,
    User,
    WhatsappFilled,
    Windy
} from '../../../../../resources/svg';

export const mapperIcons = {
    'facebook-filled': <FacebookFilled />,
    'twitter-filled': <TwitterFilled />,
    'instagram-filled': <InstagramFilled />,
    instagram: <Instagram />,
    'whatsapp-filled': <WhatsappFilled />,
    email: <EmailFilled />,
    rss: <Rss />,
    club: <Club />,
    section: <SectionFilled />,
    user: <User />,
    home: <Home />,
    rain: <Rain />,
    sun: <Sun />,
    cloudy: <Cloudy />,
    Snow: <Snow />,
    ClearNight: <ClearNight />,
    Windy: <Windy />,
    SunCloudy: <SunCloudy />,
    StormCloudy: <StormCloudy />,
    SnowCloudy: <SnowCloudy />,
    RainyCloudy: <RainyCloudy />,
    Storm: <Storm />
};
