export const mapperLogos = {
    hola: 'hola.svg',
    jardin: 'jardin.svg',
    brando: 'brando.svg',
    'data-fiscal': 'data-fiscal.svg',
    living: 'living.svg',
    lugares: 'lugares.svg',
    rolling: 'rolling.svg',
    ohlala: 'ohlala.svg',
    propiedades: 'propiedades.svg',
    campo: 'campo.svg',
    deportes: 'deportes.svg',
    'ln-logo': 'ln-logo.svg',
    'la-nacion': 'logo-lanacion.svg',
    'ios-store': 'ios-store.svg',
    'android-store': 'android-store.svg',
    'ln-mas': 'ln-mas.svg',
    bbc: 'bbc.svg',
    'logo-club': 'club.svg',
    'club-la-nacion': 'club-la-nacion.svg',
    gda: 'gda.svg',
    'ln-exclusive': 'ln-exclusive.svg'
};
