const mapperLogos = {
    hola: 'hola.svg',
    jardin: 'jardin.svg',
    brando: 'brando.svg',
    'hola-blanco': 'hola-blanco.svg',
    'jardin-blanco': 'jardin-blanco.svg',
    'brando-blanco': 'brando-blanco.svg',
    living: 'living.svg',
    lugares: 'lugares.svg',
    rolling: 'rolling.svg',
    ohlala: 'ohlala.svg',
    'living-blanco': 'living-blanco.svg',
    'lugares-blanco': 'lugares-blanco.svg',
    'rolling-blanco': 'rolling-blanco.svg',
    'ohlala-blanco': 'ohlala-blanco.svg',
    propiedades: 'propiedades.svg',
    'propiedades-blanco': 'propiedades-blanco.svg',
    campo: 'campo.svg',
    deportes: 'deportes.svg',
    bbc: 'bbc.svg',
    'bbc-blanco': 'bbc-blanco.svg',
    gda: 'gda.svg',
    ln: 'ln-exclusive.svg',
    'data-fiscal': 'data-fiscal.svg',
    'ln-logo': 'ln-logo.svg',
    'la-nacion': 'logo-lanacion.svg',
    'ios-store': 'ios-store.svg',
    'android-store': 'android-store.svg',
    'ln-mas': 'lnmas.svg',
    'lnmas-blanco': 'lnmas-blanco.svg',
    'logo-club': 'club.svg',
    'club-la-nacion': 'club-la-nacion.svg'
};

export default mapperLogos;
