import React from 'react';

import {
    FacebookFilled,
    Facebook,
    TwitterFilled,
    Twitter,
    Rss,
    Email,
    EmailFilled,
    Whatsapp,
    WhatsappFilled,
    YoutubeFilled,
    InstagramFilled,
    Instagram,
    MediumFilled,
    PinterestFilled,
    SoundcloudFilled,
    SnapchatFilled,
    TumblrFilled,
    Home,
    Sections,
    ClubCard,
    User,
    Search,
    Menu,
    Close,
    ArrowDown,
    ArrowUp,
    ArrowLeft,
    ArrowRight,
    Comment,
    Timer,
    Group,
    Zoom,
    Copy,
    Download,
    Filter,
    Fire,
    Knife,
    ShareAndroid,
    Share,
    Sun,
    Rain,
    Snow,
    Cloudy,
    Storm,
    SunCloudy,
    Windy,
    SnowCloudy,
    RainyCloudy,
    StormCloudy,
    ClearNight
} from './index';

export const mapperIcon = {
    // Social icons
    'facebook-filled': ({ ...r }) => <FacebookFilled {...r} />,
    facebook: ({ ...r }) => <Facebook {...r} />,
    'twitter-filled': ({ ...r }) => <TwitterFilled {...r} />,
    twitter: ({ ...r }) => <Twitter {...r} />,
    instagram: ({ ...r }) => <Instagram {...r} />,
    'instagram-filled': ({ ...r }) => <InstagramFilled {...r} />,
    rss: ({ ...r }) => <Rss {...r} />,
    email: ({ ...r }) => <Email {...r} />,
    'email-filled': ({ ...r }) => <EmailFilled {...r} />,
    'whatsapp-filled': ({ ...r }) => <WhatsappFilled {...r} />,
    whatsapp: ({ ...r }) => <Whatsapp {...r} />,
    'youtube-filled': ({ ...r }) => <YoutubeFilled {...r} />,
    'medium-filled': ({ ...r }) => <MediumFilled {...r} />,
    'pinterest-filled': ({ ...r }) => <PinterestFilled {...r} />,
    'soundcloud-filled': ({ ...r }) => <SoundcloudFilled {...r} />,
    'snapchat-filled': ({ ...r }) => <SnapchatFilled {...r} />,
    'tumblr-filled': ({ ...r }) => <TumblrFilled {...r} />,

    // System icons
    home: ({ ...r }) => <Home {...r} />,
    sections: ({ ...r }) => <Sections {...r} />,
    'club-card': ({ ...r }) => <ClubCard {...r} />,
    user: ({ ...r }) => <User {...r} />,
    search: ({ ...r }) => <Search {...r} />,
    menu: ({ ...r }) => <Menu {...r} />,
    close: ({ ...r }) => <Close {...r} />,
    'arrow-down': ({ ...r }) => <ArrowDown {...r} />,
    'arrow-up': ({ ...r }) => <ArrowUp {...r} />,
    'arrow-right': ({ ...r }) => <ArrowRight {...r} />,
    'arrow-left': ({ ...r }) => <ArrowLeft {...r} />,
    comment: ({ ...r }) => <Comment {...r} />,
    timer: ({ ...r }) => <Timer {...r} />,
    group: ({ ...r }) => <Group {...r} />,
    zoom: ({ ...r }) => <Zoom {...r} />,
    copy: ({ ...r }) => <Copy {...r} />,
    download: ({ ...r }) => <Download {...r} />,
    fire: ({ ...r }) => <Fire {...r} />,
    filter: ({ ...r }) => <Filter {...r} />,
    knife: ({ ...r }) => <Knife {...r} />,
    'share-android': ({ ...r }) => <ShareAndroid {...r} />,
    share: ({ ...r }) => <Share {...r} />,

    // Weather Icons
    sun: ({ ...r }) => <Sun {...r} />,
    rain: ({ ...r }) => <Rain {...r} />,
    snow: ({ ...r }) => <Snow {...r} />,
    cloudy: ({ ...r }) => <Cloudy {...r} />,
    storm: ({ ...r }) => <Storm {...r} />,
    'sun-cloudy': ({ ...r }) => <SunCloudy {...r} />,
    windy: ({ ...r }) => <Windy {...r} />,
    'snow-cloudy': ({ ...r }) => <SnowCloudy {...r} />,
    'rainy-cloudy': ({ ...r }) => <RainyCloudy {...r} />,
    'storm-cloudy': ({ ...r }) => <StormCloudy {...r} />,
    'clear-night': ({ ...r }) => <ClearNight {...r} />
};
