import { getDynamicSlotIdsByDevice } from '../utils/getDynamicSlotIdsByDevice';
import { LIVEBLOG_EDITORIAL } from '../../utils/subtypes/subtypeHelper';
import { getLiveblogDynamicSlotIdsByDevice } from '../liveblogEditorial/config';

const matchesDynamicBodySlotByDevice = {
    desktop: slotId =>
        slotId.startsWith('body_cinturon') && slotId.endsWith('_dsk'),
    mobile: slotId => slotId.startsWith('body_caja') && slotId.endsWith('_mob')
};

/**
 * Resolves dynamic banners automatically inserted in the body of the note.
 * These banners are not defined in PageBuilder and are generated by slot index.
 */
export const resolveDynamicBodyBanners = ({
    device,
    bannersToLoadFromDOM,
    bannersInBody,
    subtype = '',
    layout
}) => {
    const dynamicSlotIds =
        subtype === LIVEBLOG_EDITORIAL
            ? getLiveblogDynamicSlotIdsByDevice(device)
            : getDynamicSlotIdsByDevice({ device, subtype, layout });

    const matchesDynamicBodySlot = matchesDynamicBodySlotByDevice[device];

    const bannersInDom = bannersToLoadFromDOM
        .map(banner => banner.opt_div)
        .filter(
            optDiv =>
                (dynamicSlotIds.includes(optDiv) ||
                    (!dynamicSlotIds.length &&
                        matchesDynamicBodySlot?.(optDiv))) &&
                !bannersInBody.includes(optDiv)
        );

    bannersInBody.push(...bannersInDom);
};

/**
 * Resolves body banners manually configured in PageBuilder (Arc XP).
 * Only banners present in the DOM and matching the device suffix are considered.
 */
export const resolvePageBuilderBodyBanners = ({
    bannerInPB,
    device,
    suffix,
    bannersToLoadFromDOM,
    bannersInBody
}) => {
    Object.keys(bannerInPB)
        .filter(value => value.includes(device))
        .forEach(value => {
            const bannerSetInBody = bannerInPB[value] || '';

            return (
                !bannersInBody.includes(bannerSetInBody) &&
                bannerSetInBody.search(suffix) > -1 &&
                Object.keys(bannersToLoadFromDOM).find(
                    i => bannersToLoadFromDOM[i].opt_div === bannerSetInBody
                ) &&
                bannersInBody.push(bannerSetInBody)
            );
        });
};

/**
 * Resolves banners manually configured in PageBuilder for the notes grid.
 */
export const resolvePageBuilderGrillaBanners = ({
    bannerInPB,
    device,
    suffix,
    bannersToLoadFromDOM,
    bannersInGrillaNotas
}) => {
    Object.keys(bannerInPB)
        .filter(value => value.includes(device))
        .forEach(value => {
            const bannerSetInGrilla = bannerInPB[value] || '';

            return (
                !bannersInGrillaNotas.includes(bannerSetInGrilla) &&
                bannerSetInGrilla.search(suffix) > -1 &&
                Object.keys(bannersToLoadFromDOM).find(
                    i => bannersToLoadFromDOM[i].opt_div === bannerSetInGrilla
                ) &&
                bannersInGrillaNotas.push(bannerSetInGrilla)
            );
        });
};

const isDynamicBodyBanner = bannerConfig =>
    ['LN/DS-Body', 'LN-nota/liveblogEditorialBody'].includes(bannerConfig.type);

const isPageBuilderBodyBanner = (bannerConfig, slotGroup) =>
    (bannerConfig.type === 'LN-nota/cuerpo' ||
        bannerConfig.type === 'LN-nota/body') &&
    slotGroup === 'nota';

const isPageBuilderGrillaBanner = (bannerConfig, slotGroup) =>
    bannerConfig.type === 'LN-acumulado/grillaNotas' &&
    slotGroup === 'acumulado';

const BANNER_RESOLVERS = [
    {
        matches: isDynamicBodyBanner,
        resolve: resolveDynamicBodyBanners
    },
    {
        matches: isPageBuilderBodyBanner,
        resolve: resolvePageBuilderBodyBanners
    },
    {
        matches: isPageBuilderGrillaBanner,
        resolve: resolvePageBuilderGrillaBanners
    }
];

const bannerConfigType = props => {
    const { bannerConfig, slotGroup } = props;

    BANNER_RESOLVERS.forEach(({ matches, resolve }) => {
        if (matches(bannerConfig, slotGroup)) {
            resolve(props);
        }
    });
};

export default bannerConfigType;
